### ISSUE TITLE
Agricraft A19 Compatibility issue

### ISSUE THREAD

**Issue by illiath** [mallrat208/Multifarm-Crops#5]
Agricraft has done something "interesting" with A19, it appears that the new release has removed a function call that is being done by multifarm-crops.

In fact, A18's changelogs state they changed the API fairly significantly, however I see no information easily findable to state this is the cause of my issue below, but nor have I looked extensively into the API data.

I get the following crash on server or client when running with A19 and I attempt to autoharvest agricraft plants. (Note: Pastebin and my system are fighting with each other, and it's late, I'll link a pastebin of the full log tomorrow if it is really necessary)

<code>
[00:53:38] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoSuchMethodError: com.infinityraider.agricraft.tiles.TileEntityCrop.getFruits(Ljava/util/function/Consumer;Ljava/util/Random;)V
        at com.mr208.multifarmcrops.CropMFCAgricraftCrop.getCropDrops(CropMFCAgricraftCrop.java:62) ~[CropMFCAgricraftCrop.class:?]
        at com.mr208.multifarmcrops.CropMFCAgricraftCrop.harvestBlock(CropMFCAgricraftCrop.java:38) ~[CropMFCAgricraftCrop.class:?]
        at forestry.farming.logic.Crop.harvest(Crop.java:44) ~[Crop.class:?]
        at forestry.farming.multiblock.FarmController.cullCrop(FarmController.java:747) ~[FarmController.class:?]
        at forestry.farming.multiblock.FarmController.doWork(FarmController.java:449) ~[FarmController.class:?]
        at forestry.farming.tiles.TileFarmGearbox.updateServer(TileFarmGearbox.java:79) ~[TileFarmGearbox.class:?]
        at forestry.farming.multiblock.FarmController.updateServer(FarmController.java:267) ~[FarmController.class:?]
        at forestry.core.multiblock.MultiblockControllerBase.updateMultiblockEntity(MultiblockControllerBase.java:423) ~[MultiblockControllerBase.class:?]
        at forestry.core.multiblock.MultiblockWorldRegistry.tickStart(MultiblockWorldRegistry.java:82) ~[MultiblockWorldRegistry.class:?]
        at forestry.core.multiblock.MultiblockRegistry.tickStart(MultiblockRegistry.java:29) ~[MultiblockRegistry.class:?]
        at forestry.core.multiblock.MultiblockServerTickHandler.onWorldTick(MultiblockServerTickHandler.java:20) ~[MultiblockServerTickHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_452_MultiblockServerTickHandler_onWorldTick_WorldTickEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) ~[EventBus.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:282) ~[FMLCommonHandler.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:694) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) ~[ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_31]
[00:53:38] [Server thread/ERROR]: This crash report has been saved to: /opt/newserver/./crash-reports/crash-2017-08-10_00.53.38-server.txt
</code>

**Comment by mallrat208** [comment]
I'll check it out later this evening. Shouldn't be to hard of a fix, something similar to that must exist

**Comment by mallrat208** [comment]
Alright, Version 1.1.1 of Multifarm Crops is currently awaiting approval on Curse which restores compatibility with a19 and newer.
